version: '3.5'
services:

  app:
    build: .
    image: &app api
    restart: "no"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    env_file: &envfile
      - environment.env
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    depends_on:
      - broker
      - redis
      - postgres

  worker:
    build: .
    image: *app
    restart: "no"
    env_file: *envfile
    command: ["celery", "worker", "--app=worker.worker.app", "--concurrency=1", "--hostname=worker@%h", "--loglevel=INFO"]
    volumes:
      - ./api:/api
    depends_on:
      - broker

  flower:
    image: zoomeranalytics/flower:0.9.1-4.0.2
    restart: "no"
    env_file: *envfile
    ports:
      - "5555:5555"
    depends_on:
      - broker

  postgres:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev123

  redis:
    image: redis:3.2-alpine
    volumes:
      - redis_data:/data

  broker:
    image: rabbitmq:3
    env_file: *envfile
    ports:
      - 5672:5672
volumes:
  redis_data:
  postgres_data: