# Generated by Django 3.0 on 2019-12-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrderAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('neighborhood', models.CharField(max_length=150)),
                ('zip_code', models.CharField(max_length=12)),
                ('uf', models.CharField(max_length=12)),
            ],
        ),
    ]
