# Generated by Django 3.0 on 2019-12-20 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('phone', models.IntegerField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='UserOrderAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('neighborhood', models.CharField(max_length=150)),
                ('zip_code', models.CharField(max_length=12)),
                ('uf', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'address',
            },
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.UserOrderAddress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.User')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
