# Generated by Django 3.0 on 2019-12-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorderaddress',
            name='latitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userorderaddress',
            name='longitude',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
